import { Token } from './token';

export interface Tree {
	type: TreeType;
	start: number;
	stop: number;
	items: (Token | Tree)[];
}

export enum TreeType {
	Body,
	Statement,
	TypeStatement,
	LabeledStatement,
	FieldStatement,
	BlockStatement,
	IfStatement,
	MatchStatement,
	DefStatement,
	WhileStatement,
	DoStatement,
	ForStatement,
	ReturnStatement,
	ContinueStatement,
	BreakStatement,
	MethodStatement,
	EnumStatement,
	ExpressionStatement,
	EmptyStatement,
	ExpressionSequence,
	Expression,
	AssignmentExpression,
	TernaryExpression,
	CoalesceExpression,
	LogicalOrExpression,
	LogicalAndExpression,
	BitwiseOrExpression,
	BitwiseXorExpression,
	BitwiseAndExpression,
	EqualityExpression,
	ComparisonExpression,
	ShiftExpression,
	TermExpression,
	FactorExpression,
	RangeExpression,
	UnaryExpression,
	ReferenceExpression,
	ArrayInitializer,
	ArrayValue,
	UnionType,
	IntersectionType,
	ArrayType,
	GenericType,
	UnaryType,
	PropertyAccess,
	OptionalPropertyAccess,
	MatchOption,
	ArrayIndex,
	Parameters,
	Parameter,
	Value,
	Cast,
	Call,
	CallArgument
}